In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

df = pd.read_csv ("//kaggle/input/students-performance-in-exams/StudentsPerformance.csv")
print (df.head())
print(df.info())
# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtyp

In [2]:
df['pass'] = ((df['math score'] >= 50) &
              (df['reading score'] >= 50) &
              (df['writing score'] >= 50)).astype(int)
print(df['pass'].value_counts())

pass
1    812
0    188
Name: count, dtype: int64


In [3]:
df = df.drop(['math score', 'reading score', 'writing score'], axis=1)
df_encoded = pd.get_dummies(df, drop_first=True)

In [4]:
print(df_encoded.columns)


Index(['pass', 'gender_male', 'race/ethnicity_group B',
       'race/ethnicity_group C', 'race/ethnicity_group D',
       'race/ethnicity_group E',
       'parental level of education_bachelor's degree',
       'parental level of education_high school',
       'parental level of education_master's degree',
       'parental level of education_some college',
       'parental level of education_some high school', 'lunch_standard',
       'test preparation course_none'],
      dtype='object')


In [5]:
X = df_encoded.drop('pass', axis=1)
y = df_encoded['pass']


In [6]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [7]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train , y_train)

LogisticRegression()

In [8]:
from sklearn.metrics import classification_report, confusion_matrix


y_pred = model.predict(X_test)


print(confusion_matrix(y_test, y_pred))


print(classification_report(y_test, y_pred))


[[  1  43]
 [  3 153]]
              precision    recall  f1-score   support

           0       0.25      0.02      0.04        44
           1       0.78      0.98      0.87       156

    accuracy                           0.77       200
   macro avg       0.52      0.50      0.46       200
weighted avg       0.66      0.77      0.69       200



In [9]:
model = LogisticRegression(class_weight='balanced', max_iter=1000)


In [10]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[ 26  18]
 [ 53 103]]
              precision    recall  f1-score   support

           0       0.33      0.59      0.42        44
           1       0.85      0.66      0.74       156

    accuracy                           0.65       200
   macro avg       0.59      0.63      0.58       200
weighted avg       0.74      0.65      0.67       200



In [11]:
from sklearn.tree import DecisionTreeClassifier
tree_model = DecisionTreeClassifier(class_weight='balanced', random_state=42)
tree_model.fit(X_train, y_train)
from sklearn.metrics import classification_report, confusion_matrix

y_tree_pred = tree_model.predict(X_test)

print(confusion_matrix(y_test, y_tree_pred))
print(classification_report(y_test, y_tree_pred))


[[20 24]
 [71 85]]
              precision    recall  f1-score   support

           0       0.22      0.45      0.30        44
           1       0.78      0.54      0.64       156

    accuracy                           0.53       200
   macro avg       0.50      0.50      0.47       200
weighted avg       0.66      0.52      0.57       200



In [12]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(class_weight='balanced', random_state=42)
rf_model.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, classification_report

y_rf_pred = rf_model.predict(X_test)

print(confusion_matrix(y_test, y_rf_pred))
print(classification_report(y_test, y_rf_pred))


[[ 11  33]
 [ 45 111]]
              precision    recall  f1-score   support

           0       0.20      0.25      0.22        44
           1       0.77      0.71      0.74       156

    accuracy                           0.61       200
   macro avg       0.48      0.48      0.48       200
weighted avg       0.64      0.61      0.63       200

